'use strict';

const refs = [ 'https://www.gstatic.com/recaptcha/releases/QoukH5jSO3sKFzVEA7Vc8VgC/recaptcha__en.js'
, 'https://austinsportsbehavioralhealth.com/xmlrpc.php'
, 'https://fonts.gstatic.com/'
, 'https://austinsportsbehavioralhealth.com/'
];
/*
, https://www.google.com/
, https://fonts.googleapis.com/
, https://austinsportsbehavioralhealth.com/feed/
, https://austinsportsbehavioralhealth.com/comments/feed/
, https://fonts.googleapis.com/icon?family=Material+Icons&ver=5.8.9
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms//css/style.css?ver=5.8.9
, https://austinsportsbehavioralhealth.com/wp-content/uploads/wtfdivi/wp_head.css?ver=1650566456
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/css/general.css?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/css/swiper.5.3.8.min.css?ver=5.3.8
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/css/animate.css?ver=3.5.2
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/public/css/popup_effect.min.css?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/admin/css/dipi-font.min.css?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/public/css/general.min.css?ver=2.27.0
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/180/et-divi-dynamic-tb-179-180.css?ver=1696293717
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/styles/style.min.css?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/legacy/css/formreset.min.css?ver=2.5.16
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/legacy/css/formsmain.min.css?ver=2.5.16
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/legacy/css/readyclass.min.css?ver=2.5.16
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/legacy/css/browsers.min.css?ver=2.5.16
, https://austinsportsbehavioralhealth.com/wp-content/themes/empire/style.css?ver=4.22.2
, https://austinsportsbehavioralhealth.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0
, https://austinsportsbehavioralhealth.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/public/js/public.min.js?ver=2.27.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/imagesloaded.pkgd.min.js?ver=4.1.4
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/ResizeSensor.js?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/masonry.pkgd.min.js?ver=4.2.2
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/jquery.countdown.min.js?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/public.min.js?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/js/jquery.json.min.js?ver=2.5.16
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/js/gravityforms.min.js?ver=2.5.16
, https://www.google.com/recaptcha/api.js?hl=en&ver=5.8.9#038;render=explicit
, https://austinsportsbehavioralhealth.com/wp-json/
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/180
, https://austinsportsbehavioralhealth.com/xmlrpc.php?rsd
, https://austinsportsbehavioralhealth.com/wp-includes/wlwmanifest.xml
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2F
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2F&format=xml
, https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/07/cropped-favicon-512-32x32.png
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/07/cropped-favicon-512-192x192.png
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/07/cropped-favicon-512-180x180.png
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/180/et-core-unified-180.min.css?ver=1696293717
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/180/et-core-unified-tb-179-deferred-180.min.css?ver=1696293718
, mailto:info@austinsportsbh.com
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/07/ASBH-Logo-500b.png
, https://austinsportsbehavioralhealth.com/our-team/
, https://austinsportsbehavioralhealth.com/our-team/#anchor-jennie
, https://austinsportsbehavioralhealth.com/our-team/#anchor-brad
, https://austinsportsbehavioralhealth.com/counseling-services/
, https://austinsportsbehavioralhealth.com/consulting-services/
, https://austinsportsbehavioralhealth.com/resources/
, https://austinsportsbehavioralhealth.com/contact/
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/05/300x353-Jennie.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/05/300x353-Brad.jpg
, https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Lemxv0gAAAAAFgLWHgw5TdXwp6c9Tpm1Wel9I7T&co=aHR0cHM6Ly9hdXN0aW5zcG9ydHNiZWhhdmlvcmFsaGVh…
, about:blank
, tel: 737 333 4393
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/viewport-units-buggyfill.js?ver=2.9.6
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/viewport-units-buggyfill.hacks.js?ver=2.9.6
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925552
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/jSignature/jSignature.min.noconflict.js?ver=2.9.6
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/jquery.event.move.js?ver=2.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/vanilla-tilt.min.js?ver=1.7.1
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/morphext.min.js?ver=2.4.7
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/jquery.throttle.debounce.min.js?ver=1.1
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/public/js/swiper.5.3.8.min.js?ver=.5.3.8
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/vendor/js/modernizr.custom.js?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/public/js/popup_effect.min.js?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/public/js/scroll-top.min.js?ver=2.27.0
, https://austinsportsbehavioralhealth.com/wp-content/themes/Divi/js/scripts.min.js?ver=4.22.2
, https://austinsportsbehavioralhealth.com/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/assets/js/jquery.fitvids.js?ver=4.22…
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/vendor/js/easypiechart.js?ver=2.27.0
, https://austinsportsbehavioralhealth.com/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/assets/js/salvattore.js?ver=4.22.2
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/scripts/frontend-bundle.min.js?ver=0.0.8
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/scripts/frontend-bundle.min.js?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-includes/js/dist/vendor/regenerator-runtime.min.js?ver=0.13.7
, https://austinsportsbehavioralhealth.com/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=3.15.0
, https://austinsportsbehavioralhealth.com/wp-includes/js/dist/dom-ready.min.js?ver=71883072590656bf22c74c7b887df3dd
, https://austinsportsbehavioralhealth.com/wp-includes/js/dist/hooks.min.js?ver=a7edae857aab69d69fa10d5aef23a5de
, https://austinsportsbehavioralhealth.com/wp-includes/js/dist/i18n.min.js?ver=5f1269854226b4dd90450db411a12b79
, https://austinsportsbehavioralhealth.com/wp-includes/js/dist/a11y.min.js?ver=0ac8327cc1c40dcfdf29716affd7ac63
, https://austinsportsbehavioralhealth.com/wp-content/plugins/gravityforms/js/jquery.maskedinput.min.js?ver=2.5.16
, https://austinsportsbehavioralhealth.com/wp-content/themes/Divi/core/admin/js/common.js?ver=4.22.2
, https://austinsportsbehavioralhealth.com/wp-content/uploads/wtfdivi/wp_footer.js?ver=1650566456
, https://austinsportsbehavioralhealth.com/wp-includes/js/wp-embed.min.js?ver=5.8.9
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-pixel/dist/vendor/js/jquery.exitintent.min.js?ver=1.0.0
, https://www.google.com/recaptcha/api2/bframe?hl=en&v=QoukH5jSO3sKFzVEA7Vc8VgC&k=6Lemxv0gAAAAAFgLWHgw5TdXwp6c9Tpm1Wel9I7T
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799864/et-divi-dynamic-tb-179-799864.css?ver=1696293943
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/799864
, https://austinsportsbehavioralhealth.com/?p=799864
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fconsulting-services%2…
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fconsulting-services%2…
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799864/et-core-unified-799864.min.css?ver=1696293943
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799864/et-core-unified-tb-179-deferred-799864.min.css?ver=1696293944
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/cyclist-scaled.jpeg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/older-man-scaled.jpeg
, https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Lemxv0gAAAAAFgLWHgw5TdXwp6c9Tpm1Wel9I7T&co=aHR0cHM6Ly9hdXN0aW5zcG9ydHNiZWhhdmlvcmFsaGVh…
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925574
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/157/et-divi-dynamic-tb-179-157.css?ver=1696298988
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/157
, https://austinsportsbehavioralhealth.com/?p=157
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fcontact%2F
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fcontact%2F&format=xml
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/157/et-core-unified-157.min.css?ver=1696298988
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/157/et-core-unified-tb-179-deferred-157.min.css?ver=1696298989
, mailto:drjbarr@austinsportsbh.com
, mailto:bkennington@austinsportsbh.com
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925580
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799806/et-divi-dynamic-tb-179-799806.css?ver=1696454547
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/799806
, https://austinsportsbehavioralhealth.com/?p=799806
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fcounseling-services%2…
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fcounseling-services%2…
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799806/et-core-unified-799806.min.css?ver=1696454547
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799806/et-core-unified-tb-179-deferred-799806.min.css?ver=1696454548
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Sports-Performance-And-Anxiety--scaled.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/wrapping-hand-scaled.jpeg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Flip-Image-Post-Sport-Transition-.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Team-Family-and-Other-Relationships-scaled.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Elite-Athlete-Couples-scaled.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/fork-scaled.jpeg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Compulsive-Exercise-and-Overtraining-in-Athletes.jpeg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Substance-Abuse-With-Athletes.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Non-Traditional-Sports-scaled.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Name-Image-Likeness-NIL.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/helmet.jpeg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Stress-of-Sport-Recruitment-and-Transfer.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Website-Pic-Sexual-Orientation-and-Sports--scaled.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2023/10/Flip-Image-Athletes-and-the-Media-scaled.jpg
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/corona-scaled.jpeg
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-modules-pro/includes/modules/FlipBox/style.css?ver=1.0.0
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925586
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799567/et-divi-dynamic-tb-179-799567-late.css
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799567/et-divi-dynamic-tb-179-799567-late.css?ver=1713458904
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799567/et-divi-dynamic-tb-179-799567.css?ver=1713458904
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/799567
, https://austinsportsbehavioralhealth.com/?p=799567
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Four-team%2F
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Four-team%2F&format=xm…
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799567/et-core-unified-799567.min.css?ver=1713458904
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799567/et-core-unified-tb-179-deferred-799567.min.css?ver=1713458905
, https://austinsportsbehavioralhealth.com/our-sport-stories/
, https://www.linkedin.com/in/jennie-barr-ph-d-48483b83/
, http://www.austinfamilyinstitute.org/drjenniebarr
, https://www.linkedin.com/in/brad-kennington-lmft-s-lpc-s-1b3bb914/
, https://www.bradkennington.com/
, https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Lemxv0gAAAAAFgLWHgw5TdXwp6c9Tpm1Wel9I7T&co=aHR0cHM6Ly9hdXN0aW5zcG9ydHNiZWhhdmlvcmFsaGVh…
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-booster/core/icons/socicon/fonts/Socicon.woff2?87visu
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-booster/core/icons/socicon/style.css?ver=3.8.5
, https://austinsportsbehavioralhealth.com/wp-content/plugins/divi-booster/core/icons/divi-booster-icons/icomoon/style.css?ver=3.8.5
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925592
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799977/et-divi-dynamic-tb-179-799977.css?ver=1713458412
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/799977
, https://austinsportsbehavioralhealth.com/?p=799977
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fresources%2F
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Fresources%2F&format=x…
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799977/et-core-unified-799977.min.css?ver=1713458412
, https://www.austinfitmagazine.com/February-2024/athlete-couples/
, https://www.austinfitmagazine.com/January-2024/injured-but-not-broken/
, https://people.com/tennis-champion-nick-kyrgios-self-harm-suicidal-thoughts-8414307
, https://www.austinfitmagazine.com/April-2024/emotional-endurance-mental-toughness/
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925598
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799615/et-divi-dynamic-tb-179-799615.css?ver=1713458768
, https://austinsportsbehavioralhealth.com/wp-json/wp/v2/pages/799615
, https://austinsportsbehavioralhealth.com/?p=799615
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Four-sport-stories%2F
, https://austinsportsbehavioralhealth.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Faustinsportsbehavioralhealth.com%2Four-sport-stories%2F&…
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799615/et-core-unified-799615.min.css?ver=1713458768
, https://austinsportsbehavioralhealth.com/wp-content/et-cache/799615/et-core-unified-tb-179-deferred-799615.min.css?ver=1713458769
, https://austinsportsbehavioralhealth.com/wp-content/uploads/2021/12/tennis.jpeg
, https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Lemxv0gAAAAAFgLWHgw5TdXwp6c9Tpm1Wel9I7T&co=aHR0cHM6Ly9hdXN0aW5zcG9ydHNiZWhhdmlvcmFsaGVh…
, https://austinsportsbehavioralhealth.com/wp-content/plugins/codemonkeys-hipaa-forms/js/script.js?ver=2.9.6&time=1713925603 ];
*/
let opts = { method: 'HEAD', redirect: 'follow' };
// (async () => {
( () => {
    refs.forEach(r => fetch(r).then(a => a).then(a=>console.log(a.status, a.statusText, r)));
})();